# Generated by Django 4.1.4 on 2022-12-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=35, verbose_name='Серия')),
                ('number', models.CharField(max_length=16, verbose_name='Номер')),
                ('release_date', models.DateTimeField(verbose_name='Дата выпуска')),
                ('expiration_date', models.DateTimeField(verbose_name='Дата истечения')),
                ('last_usage_date', models.DateTimeField(verbose_name='Дата последнего использования')),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс')),
                ('status', models.CharField(choices=[('NON_ACTIVATED', 'not activated'), ('ACTIVATED', 'activated'), ('EXPIRED', 'expired')], max_length=35, verbose_name='Статус')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('KZT', 'KZT')], max_length=35, verbose_name='Валюта')),
            ],
        ),
    ]
