# Generated by Django 4.1.4 on 2022-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_usage_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего использования'),
        ),
    ]
